feat: Support `CREATE TABLE` with `ENGINE` syntax for ClickHouse
gravity-ui/sql-autocomplete-parsers pull request #78
Opened 2023-08-10 16:23 UTC by viladimiru

Closes #75

2023-08-10 16:25 UTC, viladimiru commented on src/parsing/parsers/generic/jison/create/create_table.jison
> +         keywords.push({ value: 'PARTITION BY', weight: 12 });
Previously we had wrong suggestion value actually, because `PARTITIONED BY` token not exists and this suggestion break syntax

2023-08-10 16:55 UTC, viladimiru commented on src/parsing/parsers/clickhouse/jison/create/create_table.test.json
> +    "beforeCursor": "CREATE TABLE foo (id INT, `some` FLOAT) ENGINE = ReplacingMergeTree(update_ts); ",
Case with function declaration is valid actually
[Proof](https://github.com/ClickHouse/ClickHouse/blob/1365fc91c7b7d2022509e7948dd51f2eb2dfd5cd/tests/queries/0_stateless/01906_partition_by_multiply_by_zero.sql#L9C21-L9C21)

2023-08-11 09:22 UTC, viladimiru commented on src/parsing/parsers/clickhouse/parser-extension.js
> +  parser.suggestEngines = function() {
Actually we need to make revision of suggested engines, currently I included all engines which `DataGrip` supports, except PostgreSQL.

2023-08-11 10:17 UTC, NikitaShkaruba requested changes
I'm requesting changes because it's good to keep our public API consistent. Apart from that, amazing job!

2023-08-11 10:17 UTC, NikitaShkaruba commented on src/parsing/index.ts
> +
We should remove this useless empty newline.

2023-08-11 10:17 UTC, NikitaShkaruba commented on src/parsing/index.ts
> +export function parseClickhouse(queryBeforeCursor: string, queryAfterCursor: string): ParseResult {
In our websql we are writing databases in camel case `ClickHouse`. See the function above `PostgreSql`, not `Postgresql`. Let's make it consistent here also.

2023-08-11 10:17 UTC, NikitaShkaruba commented on src/parsing/index.ts
> +    return parseClickhouse(query + ' ', '');
Let's move `query + ' '` to a separate function. We're copypasting it in 3 places

2023-08-11 13:04 UTC, NikitaShkaruba approved these changes
Waow, let's merge it

2023-08-11 13:05 UTC, merged